"""Subclass of FramePrincipal, which is generated by wxFormBuilder."""

import wx
import guiperfumes

# Implementing FramePrincipal
class ProjSisPerfumeFramePrincipal( guiperfumes.FramePrincipal ):
	def __init__( self, parent ):
		guiperfumes.FramePrincipal.__init__( self, parent )

	# Handlers for FramePrincipal events.
	def abrirMarcas()( self, event ):
		# TODO: Implement abrirMarcas()
		pass

	def abrirEssencias()( self, event ):
		# TODO: Implement abrirEssencias()
		pass

	def abrirFixacoes()( self, event ):
		# TODO: Implement abrirFixacoes()
		pass

	def abrirVolume( self, event ):
		# TODO: Implement abrirVolume
		pass

	def abrirPerfumes()( self, event ):
		# TODO: Implement abrirPerfumes()
		pass

	def abrirPerfumeEssencia()( self, event ):
		# TODO: Implement abrirPerfumeEssencia()
		pass

	def abrirSobre()( self, event ):
		# TODO: Implement abrirSobre()
		pass

	def sair()( self, event ):
		# TODO: Implement sair()
		pass


