"""Subclass of FrameMarca, which is generated by wxFormBuilder."""

import wx
import guiperfumes

# Implementing FrameMarca
class ProjSisPerfumeFrameMarca( guiperfumes.FrameMarca ):
	def __init__( self, parent ):
		guiperfumes.FrameMarca.__init__( self, parent )

	# Handlers for FrameMarca events.
	def fecharFrame()( self, event ):
		# TODO: Implement fecharFrame()
		pass

	def adicionarMarca()( self, event ):
		# TODO: Implement adicionarMarca()
		pass

	def atualizarMarca()( self, event ):
		# TODO: Implement atualizarMarca()
		pass


