"""Subclass of FramePerfumes, which is generated by wxFormBuilder."""

import wx
import guiperfumes

# Implementing FramePerfumes
class ProjSisPerfumeFramePerfumes( guiperfumes.FramePerfumes ):
	def __init__( self, parent ):
		guiperfumes.FramePerfumes.__init__( self, parent )

	# Handlers for FramePerfumes events.
	def adicionarPerfumes()( self, event ):
		# TODO: Implement adicionarPerfumes()
		pass

	def salvarPerfumes()( self, event ):
		# TODO: Implement salvarPerfumes()
		pass


