"""Subclass of FrameVolume, which is generated by wxFormBuilder."""

import wx
import guiperfumes

# Implementing FrameVolume
class ProjSisPerfumeFrameVolume( guiperfumes.FrameVolume ):
	def __init__( self, parent ):
		guiperfumes.FrameVolume.__init__( self, parent )

	# Handlers for FrameVolume events.
	def fecharFrame()( self, event ):
		# TODO: Implement fecharFrame()
		pass

	def adicionarVolume()( self, event ):
		# TODO: Implement adicionarVolume()
		pass

	def atualizarVolume()( self, event ):
		# TODO: Implement atualizarVolume()
		pass


