"""Subclass of FrameFixacoes, which is generated by wxFormBuilder."""

import wx
import guiperfumes

# Implementing FrameFixacoes
class ProjSisPerfumeFrameFixacoes( guiperfumes.FrameFixacoes ):
	def __init__( self, parent ):
		guiperfumes.FrameFixacoes.__init__( self, parent )

	# Handlers for FrameFixacoes events.
	def fecharFrame()( self, event ):
		# TODO: Implement fecharFrame()
		pass

	def adicionarFixacoes( self, event ):
		# TODO: Implement adicionarFixacoes
		pass

	def atualizarFixacoes()( self, event ):
		# TODO: Implement atualizarFixacoes()
		pass


